on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Yarn
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 18

    - name: 🔨 Build Project
      run: |
        yarn build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: code.dhamma-dullabha.org
        username: code
        local-dir: public/
        server-dir: group-sittings/
        password: ${{ secrets.password }}
